import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Provider, cacheExchange, createClient, fetchExchange } from "urql";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new ApolloClient({
  uri: "https://gorest.co.in/public/v2/graphql",
  cache: new InMemoryCache(),
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col mx-auto max-w-2xl min-h-screen">
        <NavBar />
        <div className="flex-grow bg-gray-50 p-5">{children}</div>
      </body>
    </html>
  );
}
