import "./globals.css";
import type { Metadata } from "next";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col mx-auto max-w-2xl min-h-screen">
        <NavBar />
        <div className="flex-grow bg-gray-50 p-5">{children}</div>
      </body>
    </html>
  );
}
